# Generated by Django 6.0.4 on 2026-04-16 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=150, null=True, verbose_name="ФИО")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="email")),
                ("comment", models.TextField(blank=True, null=True, verbose_name="Комментарии")),
            ],
            options={
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "message_subject",
                    models.CharField(blank=True, max_length=150, null=True, verbose_name="Тема письма"),
                ),
                ("body", models.TextField(blank=True, null=True, verbose_name="Тело письма")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["message_subject"],
            },
        ),
        migrations.CreateModel(
            name="SendingMessages",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_time", models.DateTimeField(verbose_name="Дата и время начала отправки")),
                ("end_time", models.DateTimeField(verbose_name="Дата и время окончания отправки")),
                (
                    "status",
                    models.CharField(
                        choices=[("created", "Создана"), ("launched", "Запущена"), ("completed", "Завершена")],
                        default="created",
                        max_length=15,
                        verbose_name="Статус",
                    ),
                ),
                ("client", models.ManyToManyField(to="sending.client", verbose_name="Клиент")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sending_messages",
                        to="sending.message",
                        verbose_name="Сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["message"],
            },
        ),
        migrations.CreateModel(
            name="MailingAttempts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attempt_time", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время попытки")),
                (
                    "status",
                    models.CharField(
                        choices=[("successful", "Успешно"), ("Unsuccessful", "Неуспешно")],
                        max_length=15,
                        verbose_name="Статус",
                    ),
                ),
                ("server_response", models.TextField(blank=True, null=True, verbose_name="Ответ почтового сервера")),
                (
                    "sending_messages",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="sending_messages",
                        to="sending.sendingmessages",
                        verbose_name="Рассылка сообщений",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылок",
                "verbose_name_plural": "Попытки рассылок",
                "ordering": ["attempt_time"],
            },
        ),
    ]
